version: "3"

services:
  
  openproject:
    image: openproject/community:11
    container_name: openproject
    restart: unless-stopped
    ports:
      - "8200:80"
    environment:
      - PUID=998
      - PGID=100
      - SECRET_KEY_BASE=koZirTof1faEzGv7vGyKugOq6RnpislI
    volumes:
      - ./Op/pgdata:/var/openproject/pgdata
      - ./Op/assets:/var/openproject/assets
